export const MOCK_OPPORTUNITIES = [
  {
    id: 'mock-1',
    contactName: 'Sarah Mitchell',
    company: 'Apex Roofing Co.',
    opportunityScore: 87,
    estimatedValue: '$12,000',
    reason: 'Client asked for a detailed proposal on a commercial roof replacement project. Budget pre-approved.',
    evidence: ['Requested formal quote', 'Mentioned Q1 budget availability', 'Asked for timeline'],
    recommendedAction: 'Send detailed proposal within 48 hours with competitive pricing and timeline.',
    status: 'new',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    thread: { gmailThreadId: 'mock-thread-1', subject: 'Re: Commercial Roof Replacement Quote' },
  },
  {
    id: 'mock-2',
    contactName: 'James Okonkwo',
    company: 'Okonkwo Law Firm',
    opportunityScore: 72,
    estimatedValue: '$4,500/month',
    reason: 'Law firm looking for ongoing SEO and digital marketing support. Expressed budget of $4-5k/month.',
    evidence: ['Asked about SEO retainer pricing', 'Mentioned competitor dropped the ball', 'Ready to start ASAP'],
    recommendedAction: 'Schedule discovery call and prepare a tailored SEO roadmap for legal services.',
    status: 'new',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    thread: { gmailThreadId: 'mock-thread-2', subject: 'Digital Marketing for Law Firm' },
  },
  {
    id: 'mock-3',
    contactName: 'Emily Zhao',
    company: 'Zhao Real Estate Group',
    opportunityScore: 65,
    estimatedValue: '$8,000',
    reason: 'Real estate agency interested in website redesign and lead generation setup.',
    evidence: ['Asked for web design portfolio', 'Inquired about lead gen integrations', 'Timeline: within 60 days'],
    recommendedAction: 'Send portfolio with real estate case studies and a 3-tier pricing proposal.',
    status: 'new',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    thread: { gmailThreadId: 'mock-thread-3', subject: 'Website Redesign Project' },
  },
]

export const MOCK_FOLLOWUPS = [
  {
    id: 'mock-fu-1',
    contactName: 'Tom Harrington',
    company: 'Harrington Consulting',
    lastActivity: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    daysInactive: 12,
    estimatedValue: '$6,500',
    threadSubject: 'Brand Strategy Project Proposal',
    urgency: 'high',
  },
  {
    id: 'mock-fu-2',
    contactName: 'Linda Patel',
    company: 'GreenTech Solutions',
    lastActivity: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    daysInactive: 9,
    estimatedValue: '$3,200',
    threadSubject: 'Social Media Management Quote',
    urgency: 'medium',
  },
  {
    id: 'mock-fu-3',
    contactName: 'Mark Davidson',
    company: 'Davidson Accounting',
    lastActivity: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    daysInactive: 7,
    estimatedValue: '$2,800/month',
    threadSubject: 'Monthly Reporting Retainer',
    urgency: 'medium',
  },
  {
    id: 'mock-fu-4',
    contactName: 'Rachel Torres',
    company: 'Torres Fitness Studio',
    lastActivity: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    daysInactive: 14,
    estimatedValue: '$1,500',
    threadSubject: 'Logo Design & Branding Package',
    urgency: 'high',
  },
]

export const MOCK_CHURN = [
  {
    id: 'mock-ch-1',
    client: 'Bluestone Property Management',
    churnScore: 78,
    riskLevel: 'high',
    reasons: ['Complained about delayed deliverables twice', 'Mentioned looking at other agencies', 'Response time dropped'],
    recommendedAction: 'Schedule urgent call within 24 hours. Offer a project review meeting and consider a discount on next invoice.',
    status: 'new',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'mock-ch-2',
    client: 'ClearView Windows & Doors',
    churnScore: 54,
    riskLevel: 'medium',
    reasons: ['Budget concerns mentioned', 'Replied less frequently this month', 'Asked about contract terms'],
    recommendedAction: 'Send a value recap email highlighting results achieved. Offer flexible payment options.',
    status: 'new',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_REACTIVATIONS = [
  {
    id: 'mock-re-1',
    name: 'Carlos Rivera',
    email: 'carlos@rivera-landscaping.com',
    company: 'Rivera Landscaping',
    lastContactDate: new Date(Date.now() - 92 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationReason: 'Previous client who used website design services 3 months ago. Spring season is peak for landscaping businesses.',
    recommendedOffer: 'Spring marketing campaign package with Google Ads + social media',
    emailDraft: "Hi Carlos,\n\nI hope business is going well as spring approaches! Last year's website has been performing great, and I wanted to reach out about a spring marketing push to help drive more calls during peak season.\n\nWould you be open to a quick 15-minute call this week?\n\nBest,",
    status: 'pending',
  },
  {
    id: 'mock-re-2',
    name: 'Priya Nair',
    email: 'priya@nair-consulting.com',
    company: 'Nair Business Consulting',
    lastContactDate: new Date(Date.now() - 145 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationReason: 'Former client who completed a brand refresh project. May need updated marketing materials or new campaigns.',
    recommendedOffer: 'Q2 marketing strategy refresh + LinkedIn content package',
    emailDraft: "Hi Priya,\n\nIt's been a few months since we completed your brand refresh — I hope it's been serving you well! I've been working on some new LinkedIn content strategies that have been getting great results for consultants.\n\nThought of you and wanted to check if there's anything we can do to help with your Q2 growth.\n\nWarm regards,",
    status: 'pending',
  },
  {
    id: 'mock-re-3',
    name: 'Steve Burnett',
    email: 'steve@burnett-insurance.com',
    company: 'Burnett Insurance Group',
    lastContactDate: new Date(Date.now() - 210 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationReason: 'Had a conversation about digital marketing 7 months ago but project was delayed. Decision-making window may have reopened.',
    recommendedOffer: 'Insurance industry lead generation package with Google Local Services Ads',
    emailDraft: "Hi Steve,\n\nI wanted to follow up on our conversation from earlier this year about growing your insurance book digitally. Google Local Services Ads for insurance have become incredibly effective — some of my clients are seeing a 3x increase in qualified leads.\n\nWould love to share a quick case study if you're interested.\n\nBest,",
    status: 'pending',
  },
  {
    id: 'mock-re-4',
    name: 'Megan Foster',
    email: 'megan@fosterdesignco.com',
    company: 'Foster Design Co.',
    lastContactDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationReason: 'Design studio that expressed interest in white-label content writing. Project paused due to busy season.',
    recommendedOffer: 'White-label copywriting retainer for design agencies',
    emailDraft: "Hi Megan,\n\nChecking in on the white-label copy conversation we had a couple months back. If things have settled down, I'd love to revisit — we've refined the process and onboarding is now much faster.\n\nHappy to jump on a 10-minute call if the timing is better now.\n\nBest,",
    status: 'pending',
  },
  {
    id: 'mock-re-5',
    name: 'Derek Walsh',
    email: 'derek@walshcontractors.com',
    company: 'Walsh General Contractors',
    lastContactDate: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    reactivationReason: 'Construction company that needed a website and SEO but decided to wait until after summer. Now is the right time.',
    recommendedOffer: 'Contractor website + local SEO package for fall/winter season',
    emailDraft: "Hi Derek,\n\nHope the summer build season went well! You mentioned earlier this year that fall would be a better time to invest in your online presence — that time has come.\n\nWe've helped 3 other contractors in your area double their inbound leads with our local SEO package. Would love to chat.\n\nBest,",
    status: 'pending',
  },
]

export const MOCK_METRICS = {
  totalOpportunities: 7,
  estimatedRevenue: '$47,800',
  followUpsNeeded: 4,
  churnRisks: 2,
  reactivationTargets: 5,
  lastSyncAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  isGmailConnected: false,
}
