import type { BoardData } from '@/types'

export const MOCK_BOARD: BoardData = {
  isGmailConnected: false,
  lastSyncAt: null,
  opportunities: [
    { id: 'm1', contactName: 'Alex Zhang', company: 'Apex Roofing', opportunityScore: 89, estimatedValue: '$6,000–$12,000', reason: 'Asked for a formal quote on commercial roof replacement. Budget confirmed for Q1.', evidence: ['Requested formal proposal', 'Q1 budget ready', 'Needs timeline'], suggestedAction: 'Send proposal within 48 hours with pricing and timeline', status: 'new', createdAt: new Date(Date.now() - 2 * 86400000).toISOString() },
    { id: 'm2', contactName: 'Maria Santos', company: 'Santos Law', opportunityScore: 74, estimatedValue: '$4,500/month', reason: 'Law firm needs SEO + Google Ads management. Previous agency stopped delivering results.', evidence: ['Unhappy with current agency', 'Budget $4–5k/month', 'Ready to start ASAP'], suggestedAction: 'Schedule a 30-min discovery call this week', status: 'new', createdAt: new Date(Date.now() - 4 * 86400000).toISOString() },
    { id: 'm3', contactName: 'Derek Osei', company: 'Osei Real Estate', opportunityScore: 68, estimatedValue: '$8,000', reason: 'Real estate group interested in website redesign and lead generation system.', evidence: ['Asked for portfolio', 'Timeline: 60 days', 'Budget confirmed'], suggestedAction: 'Send portfolio with real estate case studies and 3-tier pricing', status: 'new', createdAt: new Date(Date.now() - 6 * 86400000).toISOString() },
    { id: 'm4', contactName: 'Jennifer Liu', company: 'Liu Dental', opportunityScore: 55, estimatedValue: '$2,000/month', reason: 'Dental clinic asked about social media management pricing and availability.', evidence: ['Pricing inquiry', 'Needs help with Instagram'], suggestedAction: 'Send social media package pricing with dental case study', status: 'new', createdAt: new Date(Date.now() - 8 * 86400000).toISOString() },
    { id: 'm5', contactName: 'Tom Walker', company: 'Walker Contracting', opportunityScore: 62, estimatedValue: '$3,500', reason: 'General contractor wants a professional website and Google Business Profile optimization.', evidence: ['Website inquiry', 'Google Maps visibility goal'], suggestedAction: 'Send contractor website package with local SEO add-on', status: 'new', createdAt: new Date(Date.now() - 10 * 86400000).toISOString() },
  ],
  churnSignals: [
    { id: 'c1', clientName: 'Bluestone Property Mgmt', churnScore: 82, riskLevel: 'high', reasons: ['Complained about report delays twice this month', 'Mentioned looking at other agencies', 'Last 3 emails much shorter than usual'], recommendedAction: 'Call within 24 hours. Offer a live performance review session and expedited reporting.', status: 'new', createdAt: new Date(Date.now() - 1 * 86400000).toISOString() },
    { id: 'c2', clientName: 'ClearView Windows', churnScore: 58, riskLevel: 'medium', reasons: ['Asked about contract cancellation terms', 'Budget review mentioned'], recommendedAction: 'Send a value recap showing ROI from last 3 months. Offer flexible payment schedule.', status: 'new', createdAt: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: 'c3', clientName: 'Park Dental Group', churnScore: 44, riskLevel: 'medium', reasons: ['Response time slowed from same-day to 3-4 days', 'Less engaged in monthly calls'], recommendedAction: 'Send a proactive check-in with a quick wins summary. Ask if goals have changed.', status: 'new', createdAt: new Date(Date.now() - 5 * 86400000).toISOString() },
  ],
  retentionInsights: [
    { id: 'r1', clientName: 'Grace Furniture', insight: 'Mentioned planning a showroom expansion next month and wants to drive foot traffic for the grand opening.', suggestedMessage: "Hi! Excited about your expansion next month — I'd love to put together a targeted local campaign for the grand opening. Can we jump on a quick call?", timing: 'This week', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r2', clientName: 'Sunrise Landscaping', insight: 'Spring season is approaching. Client mentioned last year\'s campaign doubled their April bookings.', suggestedMessage: "Spring is almost here! Based on last year's results, I've got a few ideas to make this April even bigger. Want me to put a campaign outline together?", timing: 'Next 2 weeks', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r3', clientName: 'Metro Accounting', insight: 'Tax season is peak period. Client needs to capture SMB leads before April 15th deadline.', suggestedMessage: "Tax season is your biggest opportunity window. I want to make sure we\'re capturing every possible lead before April 15th — should we ramp up ad spend this month?", timing: 'Immediately', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r4', clientName: 'Bella Salon & Spa', insight: 'Client mentioned wanting to launch a loyalty program but hasn\'t followed up on it in 6 weeks.', suggestedMessage: "Still thinking about that loyalty program? I found a simple approach that's working really well for salons right now — happy to walk you through it in 15 minutes.", timing: 'This week', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r5', clientName: 'Westside Auto Repair', insight: 'Summer driving season is coming. Client\'s best campaigns historically run April–June.', suggestedMessage: "Your best season is just around the corner — want to plan the summer campaign now so we\'re ready to launch April 1st?", timing: 'End of month', status: 'new', createdAt: new Date().toISOString() },
  ],
  reactivationTargets: [
    { id: 'rv1', contactName: 'Carlos Rivera', email: 'carlos@riveralandscaping.com', company: 'Rivera Landscaping', lastContactDate: new Date(Date.now() - 92 * 86400000).toISOString(), history: 'Previous website design client. Project completed 3 months ago.', suggestedOffer: 'Spring Google Ads campaign to drive booking calls', suggestedMessage: "Hi Carlos, spring is here and I wanted to check in — your website has been running great! I had a few ideas for a spring Google Ads push to drive more calls during peak season. Would you be open to a quick chat?", status: 'pending' },
    { id: 'rv2', contactName: 'Priya Nair', email: 'priya@nairconsulting.com', company: 'Nair Consulting', lastContactDate: new Date(Date.now() - 145 * 86400000).toISOString(), history: 'Completed brand refresh project 5 months ago. Mentioned wanting LinkedIn content strategy.', suggestedOffer: 'LinkedIn content package for consultants', suggestedMessage: "Hi Priya, it's been a few months since your rebrand — hope it\'s been serving you well! I've been running a LinkedIn strategy for consultants that's getting great engagement. Thought of you immediately. Would you like to see what it looks like?", status: 'pending' },
    { id: 'rv3', contactName: 'Steve Burnett', email: 'steve@burnettinsurance.com', company: 'Burnett Insurance', lastContactDate: new Date(Date.now() - 210 * 86400000).toISOString(), history: 'Had a conversation about digital marketing 7 months ago. Project was delayed due to budget constraints.', suggestedOffer: 'Insurance-specific Google Local Services Ads', suggestedMessage: "Hi Steve, I've been thinking about our conversation earlier this year. Google Local Services Ads for insurance have become incredibly effective — some of my clients are 3x-ing their inbound leads. The timing might be right to revisit. Would you be open to a 15-minute catch-up?", status: 'pending' },
    { id: 'rv4', contactName: 'Megan Foster', email: 'megan@fosterdesign.com', company: 'Foster Design Co.', lastContactDate: new Date(Date.now() - 61 * 86400000).toISOString(), history: 'Design studio interested in white-label copywriting. Went cold after initial interest.', suggestedOffer: 'White-label copy retainer for design agencies', suggestedMessage: "Hi Megan, checking in on the white-label copy conversation from a couple months back. If the timing is better now, I've streamlined the process and onboarding is much faster. Happy to do a quick 10-minute call to see if it's a fit.", status: 'pending' },
    { id: 'rv5', contactName: 'Derek Walsh', email: 'derek@walshcontractors.com', company: 'Walsh Contractors', lastContactDate: new Date(Date.now() - 183 * 86400000).toISOString(), history: 'Construction company that needed website + local SEO. Put project on hold after summer.', suggestedOffer: 'Contractor website + local SEO for fall/winter season', suggestedMessage: "Hi Derek, hope the summer build season was great! You mentioned wanting to invest in your online presence once things slowed down — that time might be now. We've helped 3 other contractors in your area double their inbound leads. Want to chat?", status: 'pending' },
    { id: 'rv6', contactName: 'Lisa Chen', email: 'lisa@chenphotography.com', company: 'Chen Photography', lastContactDate: new Date(Date.now() - 75 * 86400000).toISOString(), history: 'Wedding photographer who inquired about social media content strategy.', suggestedOffer: 'Social media content calendar for wedding season', suggestedMessage: "Hi Lisa, wedding season is right around the corner! I wanted to reach out about a social media strategy that\'s been working really well for photographers — especially Instagram Reels for engagement. Would you like to see the approach?", status: 'pending' },
    { id: 'rv7', contactName: 'Ahmad Hassan', email: 'ahmad@hassanrestaurant.com', company: 'Hassan Restaurant Group', lastContactDate: new Date(Date.now() - 120 * 86400000).toISOString(), history: 'Restaurant group that wanted Google Ads + social media. Project delayed due to staffing issues.', suggestedOffer: 'Restaurant Google Ads + social media bundle', suggestedMessage: "Hi Ahmad, I hope the staffing situation has settled down! When you're ready to grow your digital presence, I'd love to put together a strategy for your restaurant group. We've helped 2 other local restaurants significantly increase reservations. Worth a 15-minute call?", status: 'pending' },
    { id: 'rv8', contactName: 'Sarah Kowalski', email: 'sarah@kowalskilaw.com', company: 'Kowalski Family Law', lastContactDate: new Date(Date.now() - 95 * 86400000).toISOString(), history: 'Family law firm that received a proposal for SEO services but didn\'t move forward.', suggestedOffer: 'Local SEO for family law — 90-day trial', suggestedMessage: "Hi Sarah, I wanted to follow up on the SEO proposal from a few months ago. I've been tracking results for a similar family law firm and the ROI has been significant. Would you be open to revisiting with a smaller trial period to see real results first?", status: 'pending' },
    { id: 'rv9', contactName: 'Marcus Johnson', email: 'marcus@johnsonfit.com', company: 'Johnson Fitness', lastContactDate: new Date(Date.now() - 55 * 86400000).toISOString(), history: 'Gym owner interested in Facebook Ads to drive memberships. Went cold after pricing discussion.', suggestedOffer: 'Facebook + Instagram ads for gym membership drive', suggestedMessage: "Hi Marcus, spring is the #1 time people sign up for gyms. I have a Facebook Ads strategy that's been driving new memberships for 2 other gyms this month — would you be interested in seeing the results?", status: 'pending' },
    { id: 'rv10', contactName: 'Nina Patel', email: 'nina@pateleducation.com', company: 'Patel Education Centre', lastContactDate: new Date(Date.now() - 160 * 86400000).toISOString(), history: 'Education centre that wanted back-to-school marketing campaign. Project paused in August.', suggestedOffer: 'End-of-year enrollment campaign + Google Ads', suggestedMessage: "Hi Nina, back-to-school season is approaching again and I wanted to reconnect! Last year you were exploring options for your enrollment campaign — I'd love to show you what we've built for similar education centres this year. Worth a quick chat?", status: 'pending' },
  ],
  summary: {
    estimatedRevenue: '$47,800',
    opportunityCount: 5,
    churnCount: 3,
    retentionCount: 5,
    reactivationCount: 10,
  },
}
