import { buildTopActions } from '@/agents/top-actions-engine'
import type { BoardData, BoardOpportunity, BoardChurnSignal, BoardReactivationTarget } from '@/types'

const mockOpportunities: BoardOpportunity[] = [
  {
    id: 'm1',
    contactName: 'Alex Zhang',
    company: 'Apex Roofing',
    opportunityScore: 89,
    revenueConfidence: 92,
    estimatedValue: '$6,000–$12,000',
    reason: 'Asked for a formal quote on commercial roof replacement. Budget confirmed for Q1.',
    evidence: ['Requested formal proposal', 'Q1 budget ready', 'Needs timeline'],
    suggestedAction: 'Send proposal within 48 hours with pricing and timeline',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'm2',
    contactName: 'Maria Santos',
    company: 'Santos Law',
    opportunityScore: 74,
    revenueConfidence: 78,
    estimatedValue: '$4,500/month',
    reason: 'Law firm needs SEO + Google Ads management. Previous agency stopped delivering results.',
    evidence: ['Unhappy with current agency', 'Budget $4–5k/month', 'Ready to start ASAP'],
    suggestedAction: 'Schedule a 30-min discovery call this week',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'm3',
    contactName: 'Derek Osei',
    company: 'Osei Real Estate',
    opportunityScore: 68,
    revenueConfidence: 71,
    estimatedValue: '$8,000',
    reason: 'Real estate group interested in website redesign and lead generation system.',
    evidence: ['Asked for portfolio', 'Timeline: 60 days', 'Budget confirmed'],
    suggestedAction: 'Send portfolio with real estate case studies and 3-tier pricing',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'm4',
    contactName: 'Jennifer Liu',
    company: 'Liu Dental',
    opportunityScore: 55,
    revenueConfidence: 58,
    estimatedValue: '$2,000/month',
    reason: 'Dental clinic asked about social media management pricing and availability.',
    evidence: ['Pricing inquiry', 'Needs help with Instagram'],
    suggestedAction: 'Send social media package pricing with dental case study',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'm5',
    contactName: 'Tom Walker',
    company: 'Walker Contracting',
    opportunityScore: 62,
    revenueConfidence: 65,
    estimatedValue: '$3,500',
    reason: 'General contractor wants a professional website and Google Business Profile optimization.',
    evidence: ['Website inquiry', 'Google Maps visibility goal'],
    suggestedAction: 'Send contractor website package with local SEO add-on',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
]

const mockChurnSignals: BoardChurnSignal[] = [
  {
    id: 'c1',
    clientName: 'Bluestone Property Mgmt',
    churnScore: 82,
    riskLevel: 'high',
    reasons: ['Complained about report delays twice this month', 'Mentioned looking at other agencies'],
    whatHappened: 'Client sent two emails this month complaining about delayed reports. In the last email they mentioned they have been "evaluating other options" and asked about the contract cancellation terms.',
    whyItMatters: 'Bluestone is one of your top 3 clients by revenue. Losing them would mean $6,500/month in recurring revenue walking out the door.',
    recommendedAction: 'Call within 24 hours. Offer a live performance review session and commit to a weekly reporting cadence.',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'c2',
    clientName: 'ClearView Windows',
    churnScore: 58,
    riskLevel: 'medium',
    reasons: ['Asked about contract cancellation terms', 'Budget review mentioned'],
    whatHappened: 'Client asked a direct question about early contract termination clauses. They followed up mentioning a "Q2 budget review" that may affect all marketing spend.',
    whyItMatters: 'If they pause during budget review, restarting momentum is difficult. A proactive call can turn this into an upsell instead of a loss.',
    recommendedAction: 'Send a value recap showing ROI from last 3 months before the budget meeting. Offer a flexible retainer option.',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'c3',
    clientName: 'Park Dental Group',
    churnScore: 44,
    riskLevel: 'medium',
    reasons: ['Response time slowed from same-day to 3-4 days', 'Less engaged in monthly calls'],
    whatHappened: 'Client used to respond to emails within hours. Over the past 3 weeks, replies have taken 3-4 days. They skipped the last monthly check-in call without notice.',
    whyItMatters: 'Silent disengagement often precedes a cancellation request. Getting ahead of this now is 10x easier than trying to win them back later.',
    recommendedAction: 'Send a proactive check-in with a quick wins summary. Ask if their goals have shifted.',
    status: 'new',
    userFeedback: null,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
]

const mockReactivationTargets: BoardReactivationTarget[] = [
  {
    id: 'rv1',
    contactName: 'Carlos Rivera',
    email: 'carlos@riveralandscaping.com',
    company: 'Rivera Landscaping',
    lastContactDate: new Date(Date.now() - 92 * 86400000).toISOString(),
    history: 'Previous website design client. Project completed 3 months ago.',
    whyContact: 'Spring is here — landscaping is entering peak season. Carlos will be busier than ever, which means he needs leads coming in now. This is the perfect window to introduce a Google Ads campaign while his competitors are still sleeping.',
    suggestedOffer: 'Spring Google Ads campaign to drive booking calls during peak season',
    suggestedMessage: "Hi Carlos, spring is here and I wanted to check in — your website has been running great! I had a few ideas for a spring Google Ads push to drive more calls during peak season. Would you be open to a quick chat?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv2',
    contactName: 'Priya Nair',
    email: 'priya@nairconsulting.com',
    company: 'Nair Consulting',
    lastContactDate: new Date(Date.now() - 145 * 86400000).toISOString(),
    history: 'Completed brand refresh project 5 months ago. Mentioned wanting LinkedIn content strategy.',
    whyContact: 'Priya specifically mentioned LinkedIn content as a next step when we wrapped the brand project. She now has fresh branding to showcase — the timing for a LinkedIn presence push is ideal.',
    suggestedOffer: 'LinkedIn content package for consultants with her new brand identity',
    suggestedMessage: "Hi Priya, it's been a few months since your rebrand — hope it's been serving you well! I've been running a LinkedIn strategy for consultants that's getting great engagement. Thought of you immediately. Would you like to see what it looks like?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv3',
    contactName: 'Steve Burnett',
    email: 'steve@burnettinsurance.com',
    company: 'Burnett Insurance',
    lastContactDate: new Date(Date.now() - 210 * 86400000).toISOString(),
    history: 'Had a conversation about digital marketing 7 months ago. Project was delayed due to budget constraints.',
    whyContact: 'Google Local Services Ads for insurance have matured significantly in the past 6 months. Steve was interested before — the product that holds him back (cost and uncertainty) is now proven in this vertical.',
    suggestedOffer: 'Insurance-specific Google Local Services Ads with pay-per-lead model',
    suggestedMessage: "Hi Steve, I've been thinking about our conversation earlier this year. Google Local Services Ads for insurance have become incredibly effective — some of my clients are 3x-ing their inbound leads. The timing might be right to revisit. Would you be open to a 15-minute catch-up?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv4',
    contactName: 'Megan Foster',
    email: 'megan@fosterdesign.com',
    company: 'Foster Design Co.',
    lastContactDate: new Date(Date.now() - 61 * 86400000).toISOString(),
    history: 'Design studio interested in white-label copywriting. Went cold after initial interest.',
    whyContact: 'Megan went quiet, not cold. Design agencies often need white-label copy but get busy. Two months is the right re-touch window — enough time to not feel pushy, close enough that she still remembers the conversation.',
    suggestedOffer: 'White-label copy retainer for design agencies — faster onboarding than before',
    suggestedMessage: "Hi Megan, checking in on the white-label copy conversation from a couple months back. If the timing is better now, I've streamlined the process and onboarding is much faster. Happy to do a quick 10-minute call to see if it's a fit.",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv5',
    contactName: 'Derek Walsh',
    email: 'derek@walshcontractors.com',
    company: 'Walsh Contractors',
    lastContactDate: new Date(Date.now() - 183 * 86400000).toISOString(),
    history: 'Construction company that needed website + local SEO. Put project on hold after summer.',
    whyContact: 'Derek said he wanted to invest in his online presence "once things slow down." The post-summer lull is exactly that window. Contractors who get online presence locked in before winter book more spring projects.',
    suggestedOffer: 'Contractor website + local SEO — lock in now before spring booking season',
    suggestedMessage: "Hi Derek, hope the summer build season was great! You mentioned wanting to invest in your online presence once things slowed down — that time might be now. We've helped 3 other contractors in your area double their inbound leads. Want to chat?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv6',
    contactName: 'Lisa Chen',
    email: 'lisa@chenphotography.com',
    company: 'Chen Photography',
    lastContactDate: new Date(Date.now() - 75 * 86400000).toISOString(),
    history: 'Wedding photographer who inquired about social media content strategy.',
    whyContact: 'Wedding season is 2-3 months away. Photographers who start their social media push now see significantly more summer booking inquiries than those who wait until April.',
    suggestedOffer: 'Social media content calendar optimized for wedding photographer bookings',
    suggestedMessage: "Hi Lisa, wedding season is right around the corner! I wanted to reach out about a social media strategy that's been working really well for photographers — especially Instagram Reels for engagement. Would you like to see the approach?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv7',
    contactName: 'Ahmad Hassan',
    email: 'ahmad@hassanrestaurant.com',
    company: 'Hassan Restaurant Group',
    lastContactDate: new Date(Date.now() - 120 * 86400000).toISOString(),
    history: 'Restaurant group that wanted Google Ads + social media. Project delayed due to staffing issues.',
    whyContact: 'Staffing issues are seasonal for restaurants. Reaching out now gives Ahmad the option to plan marketing investment for the upcoming busy period without feeling rushed.',
    suggestedOffer: 'Restaurant Google Ads + social media bundle — timed for upcoming season',
    suggestedMessage: "Hi Ahmad, I hope the staffing situation has settled down! When you're ready to grow your digital presence, I'd love to put together a strategy for your restaurant group. We've helped 2 other local restaurants significantly increase reservations. Worth a 15-minute call?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv8',
    contactName: 'Sarah Kowalski',
    email: 'sarah@kowalskilaw.com',
    company: 'Kowalski Family Law',
    lastContactDate: new Date(Date.now() - 95 * 86400000).toISOString(),
    history: "Family law firm that received a proposal for SEO services but didn't move forward.",
    whyContact: "Sarah's hesitation was likely about ROI uncertainty — a common objection for law firms. Offering a trial period removes that risk and dramatically lowers the barrier to saying yes.",
    suggestedOffer: 'Local SEO for family law — 90-day results-first trial',
    suggestedMessage: "Hi Sarah, I wanted to follow up on the SEO proposal from a few months ago. I've been tracking results for a similar family law firm and the ROI has been significant. Would you be open to revisiting with a smaller trial period to see real results first?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv9',
    contactName: 'Marcus Johnson',
    email: 'marcus@johnsonfit.com',
    company: 'Johnson Fitness',
    lastContactDate: new Date(Date.now() - 55 * 86400000).toISOString(),
    history: 'Gym owner interested in Facebook Ads to drive memberships. Went cold after pricing discussion.',
    whyContact: "Spring is the #1 time people sign up for gyms. Marcus has a 6-week window to capture new member momentum before it peaks. The pricing concern can be handled with a performance-based structure.",
    suggestedOffer: 'Spring membership drive via Facebook + Instagram ads — pay for results',
    suggestedMessage: "Hi Marcus, spring is the #1 time people sign up for gyms. I have a Facebook Ads strategy that's been driving new memberships for 2 other gyms this month — would you be interested in seeing the results?",
    status: 'pending',
    userFeedback: null,
  },
  {
    id: 'rv10',
    contactName: 'Nina Patel',
    email: 'nina@pateleducation.com',
    company: 'Patel Education Centre',
    lastContactDate: new Date(Date.now() - 160 * 86400000).toISOString(),
    history: 'Education centre that wanted back-to-school marketing campaign. Project paused in August.',
    whyContact: 'Education centres need 2-3 months of lead time to fill classes. Starting the conversation now means Nina can have a campaign running well before next enrollment season.',
    suggestedOffer: 'End-of-year enrollment campaign + Google Ads for summer programs',
    suggestedMessage: "Hi Nina, back-to-school season is approaching again and I wanted to reconnect! Last year you were exploring options for your enrollment campaign — I'd love to show you what we've built for similar education centres this year. Worth a quick chat?",
    status: 'pending',
    userFeedback: null,
  },
]

export const MOCK_BOARD: BoardData = {
  isGmailConnected: false,
  lastSyncAt: null,
  topActions: buildTopActions(mockOpportunities, mockChurnSignals, mockReactivationTargets),
  opportunities: mockOpportunities,
  churnSignals: mockChurnSignals,
  retentionInsights: [
    { id: 'r1', clientName: 'Grace Furniture', insight: 'Mentioned planning a showroom expansion next month and wants to drive foot traffic for the grand opening.', suggestedMessage: "Hi! Excited about your expansion next month — I'd love to put together a targeted local campaign for the grand opening. Can we jump on a quick call?", timing: 'This week', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r2', clientName: 'Sunrise Landscaping', insight: "Spring season is approaching. Client mentioned last year's campaign doubled their April bookings.", suggestedMessage: "Spring is almost here! Based on last year's results, I've got a few ideas to make this April even bigger. Want me to put a campaign outline together?", timing: 'Next 2 weeks', status: 'new', createdAt: new Date().toISOString() },
    { id: 'r3', clientName: 'Metro Accounting', insight: 'Tax season is peak period. Client needs to capture SMB leads before April 15th deadline.', suggestedMessage: "Tax season is your biggest opportunity window. I want to make sure we're capturing every possible lead before April 15th — should we ramp up ad spend this month?", timing: 'Immediately', status: 'new', createdAt: new Date().toISOString() },
  ],
  reactivationTargets: mockReactivationTargets,
  summary: {
    estimatedRevenue: '$47,800',
    opportunityCount: 5,
    churnCount: 3,
    retentionCount: 3,
    reactivationCount: 10,
  },
}
